### ISSUE TITLE
Change storage for image

### ISSUE THREAD

**Issue by Reflow1319** [remipou/nova-page-manager#17]
Could you add a config option to change the upload location of the image?

A config option like this  " pagemanager.image_disk
would look something like this 

```
Image::make(__('OG image'), 'og_image')
                ->disk(' pagemanager.image_disk ')
                ->path(config('pagemanager.images_location'))
                ->storeOriginalName('og_image_name')
                ->prunable()
                ->hideFromIndex(),

```

**Comment by remipou** [comment]
yes i can have a look into it but feel free to submit a PR.

**Comment by remipou** [comment]
https://github.com/remipou/nova-page-manager/pull/18
