### ISSUE TITLE
Declaration of Remipou\Nova Page Manager\Page::sluggable() must be compatible with Cviebrock\Eloquent Sluggable\Sluggable::sluggable(): array

### ISSUE THREAD

**Issue by AshutoshJha15** [remipou/nova-page-manager#37]
I am getting this error after composer upgrade

**Comment by remipou** [comment]
Hi, thank you for reporting this! 
This [commit](https://github.com/remipou/nova-page-manager/commit/baa46ad1e3496597b204060025ad88d73421636a) should fix it.
Try updating to 1.0.15
