### ISSUE TITLE
Recommended Route breaks admin

### ISSUE THREAD

**Issue by kikoseijo** [remipou/nova-page-manager#6]
Hi there, great package, thanks for the work!

If I ad your recommendation to the routes it breaks the admin interface. 
It seems intercepting internal nova requests.

Im on the latest version and todays brand new install. 
Did customise the path using the `nova.php` for "/back"

Just for your knowledge.

**Comment by remipou** [comment]
i did update Nova now but could not reproduce. what happens exactly?

**Comment by kikoseijo** [comment]
Looking at it right now, and seems the problem being intercepted by the nova.
Not sure could be here `->where('slug', '^((?!' . trim(config('nova.path'), '/') . ').)*$');`

But when I active  the route nova admin breaks and all calls are lost.


![screen shot 2018-11-12 at 22 44 12](https://user-images.githubusercontent.com/1528668/48376908-99a14500-e6cc-11e8-8a2f-a8558bfa99d5.png)

**Comment by kikoseijo** [comment]
Im on laravel 5.7.

**Comment by kikoseijo** [comment]
Ok, found it. 
Seems the default path `nova` match the internal api `nova-api` and because of this on a clean install will work, will fail if you change this to anything different to `nova`-

Not sure if you can make a more complex RegEx- Out of my scope.

**Comment by kikoseijo** [comment]
Here you are the solution 

```
Route::get('{slug}/{param?}', '\Remipou\NovaPageManager\PageController@page')
	->where('slug', '^((?!' . trim(config('nova.path'), '/') . '|nova-api).)*$');
```

Was quite simple.

**Comment by remipou** [comment]
great, thanks. i'll update the readme

**Comment by kikoseijo** [comment]
Change it to `nova-` to cover also the route to `nova-vendors` with `nova-api`

Cheers, great package.
